name: 'Rebound lueur'
description: 'Run a lueur scenario'
author: 'Rebound'
branding:
  icon: "check-circle"
  color: "red"
inputs:
  github-token:
    description: "The GitHub token to commit the results"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install lueur
      shell: bash
      run: |
        curl -s -Lo lueur https://github.com/Lawouach/demo/releases/download/1/lueur
        chmod +x lueur

        export PATH=`pwd`:$PATH

        lueur --version
