name: 'Rebound lueur'
description: 'Run a lueur scenario'
author: 'Rebound'
branding:
  icon: "check-circle"
  color: "red"
inputs:
  scenario:
    description: "Path to a lueur scenario file or a directory containing scenario files"
    required: true
  report:
    description: "Path where to store the generated report"
    required: false
    default: "./report.md"
  results:
    description: "Path where to store the scenario results"
    required: false
    default:  "./results.json"
runs:
  using: "composite"
  steps:
    - name: Install lueur
      shell: bash
      run: |
        curl -s -Lo lueur https://github.com/Lawouach/demo/releases/download/1/lueur
        chmod +x lueur

        ./lueur --version

    - name: Run scenarios
      shell: bash
      run: |
        ./lueur scenario run \
          --scenario ${{ inputs.scenario }} \
          --report ${{ inputs.report }} \
          --result ${{ inputs.result }}